#!/bin/bash
# Version 4

plasmoidName=termoid
plasmoidName="${plasmoidName##*.}" # Strip namespace (Eg: "org.kde.plasma.")
plasmoidVersion=0.5
rm ${plasmoidName}-v*.plasmoid
cd package
filename=${plasmoidName}-v${plasmoidVersion}.plasmoid
zip -r $filename *
mv $filename ../$filename
cd ..
echo "md5: $(md5sum $filename | awk '{ print $1 }')"
echo "sha256: $(sha256sum $filename | awk '{ print $1 }')"
